### ISSUE TITLE
mapa mental

### ISSUE THREAD

**Issue by mae18-25** [SistemasTecTlaxiaco/actividad-4-mapa-mental-mae18-25#2]
[mapa mental dulce maetzy.pdf](https://github.com/user-attachments/files/17092332/mapa.mental.dulce.maetzy.pdf)

**Comment by Ivan-PerezZ** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:5/5
Referencias:5/5
Calificación Final:20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
